### ISSUE TITLE
Add the topic datenstrom-yellow

### ISSUE THREAD

**Issue by markseuffert** [zenblom/yellow-clarity#1]
Hello Martin!

Here's a tip from the Datenstrom Yellow maintainers. Please add the topic `datenstrom-yellow` to your repository. https://github.com/topics/datenstrom-yellow

Thanks for developing/designing extensions, this is much appreciated. 👍

**Comment by zenblom** [comment]
Hi Mark!
I was not aware of the topic but it is now added.
